module.exports = {
  sheet1: {
    id: 1,
    name: 'Javier',
    first_surname: 'Cansado',
    zone: 'Chiclayo',
    address: 'Pueblo Joven 5 de Noviembre 43, Chiclayo',
    id_number: '23344546x',
    complete: false,
    second_surname: null,
    birthday: null,
    photos_family: null,
    photos_house: null,
    family_inCharge: null,
    family_information: null,
    education_center: null,
    social_situation: null,
    medical_therapies: null,
    medical_diagnose: null,
    medical_mobility: null,
    medical_wheel_chair: null,
    medical_comunication: null,
    medical_tests: null,
    medical_treatment: null,
    medical_relative_disease: null,
    home_own_rent: null,
    home_material: null,
    home_facilities: null,
    home_num_rooms: null,
    home_numBeds: null,
    home_forniture: null,
    home_salubrity: null,
    economic_familiar_income: null,
    economic_external_support: null,
    economic_feeding_center: null,
    economic_others: null,
    general_information: null,
    manifested_information: null,
    detected_information: null,
    warning_information: null
  },
  sheet2: {
    name: 'Jose',
    first_surname: 'Perez',
    address: 'Pueblo Joven 5 de Noviembre 43, Chiclayo',
    zone: 'Chiclayo',
    help: false,
    id: 2,
    complete: false,
    second_surname: null,
    birthday: null,
    photos_family: null,
    photos_house: null,
    family_inCharge: null,
    family_information: null,
    education_center: null,
    social_situation: null,
    medical_therapies: null,
    medical_diagnose: null,
    medical_mobility: null,
    medical_wheel_chair: null,
    medical_comunication: null,
    medical_tests: null,
    medical_treatment: null,
    medical_relative_disease: null,
    home_own_rent: null,
    home_material: null,
    home_facilities: null,
    home_num_rooms: null,
    home_numBeds: null,
    home_forniture: null,
    home_salubrity: null,
    economic_familiar_income: null,
    economic_external_support: null,
    economic_feeding_center: null,
    economic_others: null,
    general_information: null,
    manifested_information: null,
    detected_information: null,
    warning_information: null
  },
  user1: {
    id: 1,
    name: 'Alber',
    first_surname: 'Lolo',
    second_surname: 'Aria',
    nickname: 'Sonya',
    email: 'sonialolo@gmail.com',
    password: 'kilombo',
    birthday: '1984-01-12',
    studies: [
      'journalism',
      'psychology'
    ],
    professions: [
      'teacher',
      'psychologist'
    ],
    prev_volunteering: [
      'AMI3'
    ],
    role: 'admin'
  },
  state1: {
    id: 1,
    prev_state_id: null,
    value: {
      start_year: 2017,
      name: 'Autism',
      observations: ''
    },
    user_id: 1,
    remote_id: 1,
    remote_collection: 'sheet',
    field_name: 'medical_diagnose'
  },
  state2: {
    prev_state_id: 1,
    id: 2,
    value: {
      name: 'Down Sindrome',
      start_year: 1996
    },
    user_id: 1,
    remote_id: 1,
    remote_collection: 'sheet',
    field_name: 'medical_diagnose'
  },
  state3: {
    prev_state_id: null,
    id: 3,
    value: {
      name: 1,
      start_year: 1996
    },
    user_id: 1,
    remote_id: 1,
    remote_collection: 'sheet',
    field_name: 'medical_mobility'
  }
}
